name: Waka Readme Stats

on:
  schedule:
    # Roda todo dia às 12am IST (18:30 no seu fuso horário de Adamantina)
    - cron: '30 18 * * *'
  workflow_dispatch: # Permite rodar manualmente

jobs:
  update-readme:
    name: Update Readme with WakaTime Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
