name: Update Pinned Repositories
on:
  schedule:
    # Roda a cada 12 horas
    - cron: '0 12 * * *'
  workflow_dispatch:
    # Adiciona um botão para rodar manualmente na aba Actions
jobs:
  update-readme:
    name: Update Pinned Repos
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        run: python scripts/update_repos.py
      
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '🔄 Update pinned repositories on README'
          file_pattern: README.md
